provider: mock

defaults:
  model: gpt-4o-mini
  temperature: 0.0

mocks:
  invoice_spec_agent:
    name: invoice-spec-agent
    version: 1
    response_path: ./mock/specs/invoice-verification.json

providers:
  mock:
    enabled: true
  openai:
    enabled: false
    api_key: ""
  azure_openai:
    enabled: false
    api_key: ""
    endpoint: ""
    deployment_name: ""
    api_version: "2024-02-15-preview"

