components:
  - id: text_input
    name: Text Input Field
    category: form
    description: "Captures a single line of user input"
    applicable_app_types:
      - TYPE_DOCUMENT_PROCESSOR
      - TYPE_VALIDATION
    props:
      label:
        type: string
        required: true
      placeholder:
        type: string
        required: false
      binding:
        type: string
        required: true
      required:
        type: boolean
        required: false

  - id: textarea
    name: Textarea
    category: form
    description: "Captures multi-line user input"
    applicable_app_types:
      - TYPE_DOCUMENT_PROCESSOR
    props:
      label:
        type: string
        required: true
      placeholder:
        type: string
        required: false
      binding:
        type: string
        required: true

  - id: file_upload
    name: File Upload
    category: input
    description: "Allows uploading a document for processing"
    applicable_app_types:
      - TYPE_DOCUMENT_PROCESSOR
    props:
      label:
        type: string
        required: true
      accept:
        type: array
        items: string
        required: false
      binding:
        type: string
        required: true

  - id: validation_summary
    name: Validation Summary
    category: output
    description: "Displays validation results with error list"
    applicable_app_types:
      - TYPE_VALIDATION
      - TYPE_DOCUMENT_PROCESSOR
    props:
      title:
        type: string
        required: true
      binding:
        type: string
        required: true

  - id: submit_button
    name: Submit Button
    category: action
    description: "Triggers validation or processing pipeline"
    applicable_app_types:
      - TYPE_DOCUMENT_PROCESSOR
      - TYPE_VALIDATION
    props:
      label:
        type: string
        required: true
      action:
        type: string
        required: true

