user:
  id: demo-user
  email: demo@example.com

project:
  id: invoice-verification-mvp
  name: "Invoice Verification Assistant"
  description: "Generates a mock invoice verification web app for finance teams."

llm:
  use_mock: true
  requirements_prompt: "Generate an invoice validation assistant that processes uploaded invoices and highlights anomalies."

mock:
  spec_id: invoice-verification

options:
  include_playwright: true
  include_docker: true
  include_logging: true

